### ISSUE TITLE
es5 ?

### ISSUE THREAD

**Issue by irom77** [taraslayshchuk/es2csv#19]
Does it work with es5 ?

**Comment by taraslayshchuk** [comment]
Not yet.

**Comment by vsafin-copart** [comment]
Seems like all thats needed is to replace elasticsearch version to 5.1.* in requirements.txt

**Comment by taraslayshchuk** [comment]
No, there are a few changes in elasticsearch-py library, which should be implemented.

**Comment by vsafin-copart** [comment]
You are right i also had to comment      **search_type='scan'** and was able to run with elasticsearch 5.1.0 just fine..

**Comment by taraslayshchuk** [comment]
You did not check all of arguments. For example *fields* param is not present in [search](http://elasticsearch-py.readthedocs.io/en/master/api.html?highlight=scroll#elasticsearch.Elasticsearch.search) method.

**Comment by vsafin-copart** [comment]
Correct. I did not use fields param. Thank you, Taras. Its a very nice utility. ES 5 is becoming more mainstream - elastic.co hosting ES5 with their cloud offering

**Comment by elmalto** [comment]
Works for me, too. Thank you!

**Comment by taraslayshchuk** [comment]
ES 5 support has been added in [5.2.0](https://github.com/taraslayshchuk/es2csv/releases/tag/5.2.0) release. Please check.
