### ISSUE TITLE
Is there a way to force the columns order in output?

### ISSUE THREAD

**Issue by karthikdivi** [taraslayshchuk/es2csv#21]
es2csv is not honouring the order of specified columns. For example if it write -f b a in the output csv i see a column first.

**Comment by taraslayshchuk** [comment]
This question was already [asked](https://github.com/taraslayshchuk/es2csv/issues/14#issuecomment-255860304). So let me explain why it is sorted.
When you are using -f you will ask elasticsearch for specific fields, but they can be missing in ES.
Thats way es2csv don't care about order of asked fields (ES already returns fields in wrong order). So best solution for me was just sort them in alphabetic. Any way you can move columns in your favorite editor (MS Office, LibreOffice).

**Comment by taraslayshchuk** [comment]
Hello, @karthikdivi, please check [2.4.2](https://github.com/taraslayshchuk/es2csv/releases/tag/2.4.2) release, this should fix columns order.

**Comment by karthikdivi** [comment]
Awesome @taraslayshchuk 
Thanks again for the great tool.
