### ISSUE TITLE
Not able to fetch more than 1000 records

### ISSUE THREAD

**Issue by sreejithps303** [taraslayshchuk/es2csv#30]
Hi,

I am not able to export more than 10000 records. it is only exporting when m and s value is same. as "s" has max 10k . so it max export 10k records.

**Comment by eduardofv** [comment]
The -s parameter is for the "scroll size". That is, the size of the batch each request retrieves. If you set -s 10000 and leave out -m you should be able to export everything in the smallest number of requests.

**Comment by eduardofv** [comment]
BTW, if -m is zero it means it will retrieve everything, not zero results.

**Comment by taraslayshchuk** [comment]
Hello,

Please provide more information: OS, python version, es2csv version, elasticsearch version and run arguments.
