### ISSUE TITLE
'unicode' is not defined

### ISSUE THREAD

**Issue by nthx** [taraslayshchuk/es2csv#39]
I've just downloaded & run it on debian and it gives me this:

```
  File "/usr/local/lib/python3.4/dist-packages/es2csv.py", line 237, in <dictcomp>
    line_dict_utf8 = {k: v.encode('utf8') if isinstance(v, unicode) else v for k, v in line_as_dict.items()}
NameError: name 'unicode' is not defined
```

I've hacked the file and modified `unicode -> str` and it worked

Hope it helps..

**Comment by jayjanssen** [comment]
ditto, thanks for the quick hack @nthx

**Comment by jayjanssen** [comment]
This is actually an issue if you use python3.  Python2 doesn't have this issue.  With P3, I got my strings outputted as byte characters, e.g., "b'some string'", which was undesirable for me.

**Comment by taraslayshchuk** [comment]
Please use python2, python3 not supported yet.
