### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by rdica** [taraslayshchuk/es2csv#41]
I think I asked about this before, but I can't find any emails, and I didn't file as issue here.

Is there a means to sort the output based on a specified field?

**Comment by taraslayshchuk** [comment]
If you are using raw query you could sort based on query:
```
es2csv -q '{"sort" : [{"key":"desc"}], "query" : {"term" : { "tags" : "qa" }}}' --raw --debug -e -o out.csv -f key tags
Using these indices: logstash-*.
Query[Query DSL]: {"sort": [{"key": "desc"}], "query": {"term": {"tags": "qa"}}}.
Output field(s): key, tags.
Found 5 results.
```
Looks like it could be implemented with --sort arg.
> sort – A comma-separated list of field:direction pairs

**Comment by taraslayshchuk** [comment]
Added --sort(S) in [5.5.2](https://github.com/taraslayshchuk/es2csv/tree/5.5.2).
