### ISSUE TITLE
how to read the query string from file?

### ISSUE THREAD

**Issue by iamtiancaif** [taraslayshchuk/es2csv#5]
sometimes i need to use terms query which include 10-thousands of uid. 
It take a long time to paste the whole command in console window.

thanks~

**Comment by iamtiancaif** [comment]
and then i get this result. T-T

bash: /usr/local/bin/es2csv: Argument list too long

**Comment by taraslayshchuk** [comment]
Yes, there is [ARG_MAX](http://www.in-ulm.de/~mascheck/various/argmax/) limitation for different OS.
I added option to read query from file, example:
```bash
$ es2csv -q @'query string.json' -o out.csv -r -i index*
Found 1 results
Run query [###################] [1/1] [100%] [0:00:00] [Time: 0:00:00] [239.80  docs/s]
Write to csv [###############] [1/1] [100%] [0:00:00] [Time: 0:00:00] [  2.33 klines/s]
```
This changes are in [query_string_from_file branch](https://github.com/taraslayshchuk/es2csv/tree/query_string_from_file). 
```bash 
$ pip uninstall es2csv
$ pip install git+https://github.com/taraslayshchuk/es2csv.git@query_string_from_file
```
Could you please test it?

**Comment by iamtiancaif** [comment]
Thank you so much, i'll test it this week. 😘

**Comment by taraslayshchuk** [comment]
Hey, @iamtiancaif! How's it going?

**Comment by iamtiancaif** [comment]
Hi, @taraslayshchuk ! It worked pretty well. I just forgot to tell you about it.
Thanks for your wonderful work!!

![picture1](https://cloud.githubusercontent.com/assets/5001927/15986243/7a6b63a0-3035-11e6-933d-9edafa4d0427.png)
