### ISSUE TITLE
Export _score and _id

### ISSUE THREAD

**Issue by voyager-data** [taraslayshchuk/es2csv#6]
When I add _score or _id to the list of export fields, the resulting file has neither column. Is this expected behavior? Getting the relevancy score with results is important to my use case.

Thank you!

**Comment by taraslayshchuk** [comment]
Hi!

I have never used this fields. I added `-e` arg for exporting [meta-fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-fields.html): _id, _index, _type, _score. Changes are in [export_meta_fields](https://github.com/taraslayshchuk/es2csv/tree/export_meta_fields) branch.
```bash
$ pip uninstall es2csv
$ pip install git+https://github.com/taraslayshchuk/es2csv.git@export_meta_fields
````
Could you please test it?

**Comment by voyager-data** [comment]
Works like a charm! Thank you!

**Comment by voyager-data** [comment]
It works for me. Thank you!

**Comment by taraslayshchuk** [comment]
Awesome! I am going to release new version with this bugfix into [pypi](https://pypi.python.org/pypi/es2csv). Stay tuned!
