### ISSUE TITLE
python error?

### ISSUE THREAD

**Issue by freemti** [taraslayshchuk/es2csv#8]
[a408186@masnussyslog python]$ sudo es2csv -v -q 'host.raw: eosn*' -o eosn.txt        
Traceback (most recent call last):
  File "/usr/bin/es2csv", line 7, in <module>
    from es2csv import main
  File "/usr/lib/python2.6/site-packages/es2csv.py", line 197
    out = {field: hit[field] for field in META_FIELDS} if self.opts.meta_fields else {}
                               ^
SyntaxError: invalid syntax

**Comment by taraslayshchuk** [comment]
Currently this tool supports only python 2.7.*.
